[build]
  command = "npm install && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.19.0"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "false"
  NEXT_PHASE = "production"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  PATH = "/opt/buildhome/.nvm/versions/node/v18.19.0/bin:/opt/buildhome/.cargo/bin:/opt/buildhome/.local/bin:/opt/buildhome/bin:/opt/buildhome/.local/bin:/opt/buildhome/.nvm/versions/node/v18.19.0/bin:/opt/buildhome/.cargo/bin:/opt/buildhome/.local/bin:/opt/buildhome/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"] 