[build]
  command = "npm install && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.19.0"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "false"
  NEXT_PHASE = "production"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 